language: node_js
node_js:
  - "10"
services:
  - docker

before_install:
  - sudo mkdir -p /usr/share/fonts/opentype/
  - sudo mkdir -p /usr/share/fonts/truetype/
  - sudo mv ./fonts/Adobe-FangSong-Std-R-2 /usr/share/fonts/opentype/
  - sudo mv ./fonts/WeiRuanYaHei-1 /usr/share/fonts/truetype/
  - fc-list :lang=zh
  - npm install

script:
  - npm run pub
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t afuning/basic:latest .
  - docker push afuning/basic:latest