language: node_js
node_js:
  - "10"
services:
  - docker

before_install:
  - sudo apt install -y --force-yes --no-install-recommends fonts-wqy-microhei
  - sudo apt install -y --force-yes --no-install-recommends ttf-wqy-zenhei
  - npm install

script:
  - npm run pub
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t afuning/basic:latest .
  - docker push afuning/basic:latest