language: node_js
node_js:
  - "10"
services:
  - docker

before_install:
  - sudo apt-get install ttf-mscorefonts-installer
  - sudo apt-get install fontconfig
  - sudo mkdir -p /usr/share/fonts/opentype/
  - sudo mkdir -p /usr/share/fonts/truetype/
  - sudo mv ./fonts/Adobe-FangSong-Std-R-2.otf /usr/share/fonts/opentype/
  - sudo mv ./fonts/WeiRuanYaHei-1.ttf /usr/share/fonts/truetype/
  - sudo mkfontscale
  - sudo mkfontdir
  - sudo fc-cache -fv
  - fc-list :lang=zh
  - npm install

script:
  - npm run pub
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t afuning/basic:latest .
  - docker push afuning/basic:latest